assessment = [
    {
        "name": "Physical Activity",
        "questions": [
            {
                "question": "What is the max amount of push-ups you can do in one go?",
                "id": "max_push_ups",
                "insight": "Upper body pushing strength",
                "category": "strength",
                "description": "",
                "options": ["50+", "30-50", "15-30", "5-15", "Under 5"],
                "curve": [100, 82, 60, 40, 10],
                "weight": 0.2,
            },
            {
                "question": "What is the max amount of pull-ups you can do in one go?",
                "id": "max_pull_ups",
                "insight": "Upper body pulling strength",
                "category": "strength",
                "description": "Scapula fully rotated at the bottom, chin above the bar at the top.",
                "options": ["15+", "8-14", "3-7", "1-2", "None"],
                "curve": [100, 82, 60, 35, 5],
                "weight": 0.2,
            },
            {
                "question": "What's your strength total? (Squat + Bench + Deadlift)?",
                "id": "strength_total",
                "insight": "Overall muscular strength",
                "category": "strength",
                "description": "Add your best squat, bench, and deadlift together.",
                "options": [
                    "Over 450 kg (1000 lbs)",
                    "320-450 kg (700-1000 lbs)",
                    "180-320 kg (400-700 lbs)",
                    "Under 180 kg (400 lbs)",
                    "I don't lift / don't track",
                ],
                "curve": [100, 82, 60, 35, None],
                "weight": 0.3,
            },
            {
                "question": "How long can you hang from a pull-up bar without letting go?",
                "id": "dead_hang_time",
                "insight": "Grip strength & muscular endurance",
                "category": "strength",
                "description": "",
                "options": [
                    "Over 90 seconds",
                    "60-90 seconds",
                    "30-59 seconds",
                    "10-29 seconds",
                    "less than 10 seconds",
                ],
                "curve": [100, 82, 60, 35, 10],
                "weight": 0.15,
            },
            {
                "question": "How many days per week do you resistance train?",
                "id": "resistance_training_days",
                "insight": "Resistance training consistency",
                "category": "strength",
                "description": "Activities where your muscles counter external load (dumbbells, bands, body weight etc.).",
                "options": ["5+ days", "3-4 days", "1-2 days", "Rarely or never"],
                "curve": [100, 80, 55, 20],
                "weight": 0.15,
            },
            {
                "question": "How much zone 2 cardio do you get per week?",
                "id": "zone_2_cardio",
                "insight": "Aerobic endurance",
                "category": "cardio",
                "description": "Easy pace where you can still hold a conversation. Brisk walking, hiking, easy cycling.",
                "options": ["3+ hours", "2-3 hours", "1-2 hours", "Under 1 hour"],
                "curve": [100, 80, 60, 35],
                "weight": 0.2,
            },
            {
                "question": "How much zone 4 cardio do you get per week?",
                "id": "zone_4_cardio",
                "insight": "High-intensity cardiovascular fitness",
                "category": "cardio",
                "description": "Hard efforts where you can barely speak. Sprints, intervals, hill runs, last 30s of an all-out set.",
                "options": [
                    "45+ minutes",
                    "30-45 minutes",
                    "15-30 minutes",
                    "Under 15 minutes",
                ],
                "curve": [100, 80, 60, 30],
                "weight": 0.15,
            },
            {
                "question": "Average amount of steps per day",
                "id": "daily_steps",
                "insight": "Daily physical activity",
                "category": "cardio",
                "description": "",
                "options": [
                    "12000+",
                    "8000-12000",
                    "5000-8000",
                    "3000-5000",
                    "Under 3000",
                ],
                "curve": [100, 85, 70, 50, 25],
                "weight": 0.1,
            },
            {
                "question": "How long could you continuously jog at an easy pace today without stopping?",
                "id": "continuous_jog_time",
                "insight": "Cardiovascular endurance",
                "category": "cardio",
                "description": "",
                "options": [
                    "Over 60 minutes",
                    "30-60 minutes",
                    "15-30 minutes",
                    "5-15 minutes",
                    "Under 5 minutes or unable to",
                ],
                "curve": [100, 82, 60, 35, 10],
                "weight": 0.25,
            },
            {
                "question": "Standing with legs straight, how close do you get to touching your toes?",
                "id": "toe_touch_flexibility",
                "insight": "Posterior chain flexibility",
                "category": "flexibility",
                "description": "",
                "options": [
                    "Palms flat on floor",
                    "Fingertips touch toes or floor",
                    "Reach shins or ankles",
                    "Reach knees or higher",
                    "Can barely bend forward",
                ],
                "curve": [100, 82, 60, 35, 10],
                "weight": 0.35,
            },
            {
                "question": "Can you sit in a deep squat (heels flat, hips below knees) for 60 seconds?",
                "id": "deep_squat_hold",
                "insight": "Hip, ankle & squat mobility",
                "category": "flexibility",
                "description": "",
                "options": [
                    "Easily",
                    "With mild discomfort",
                    "For about 30 seconds",
                    "Less than 15 seconds",
                    "Cannot",
                ],
                "curve": [100, 85, 60, 35, 10],
                "weight": 0.35,
            },
            {
                "question": "Can you clasp your hands behind your back (one over shoulder, one behind)?",
                "id": "shoulder_mobility",
                "insight": "Shoulder mobility",
                "category": "flexibility",
                "description": "",
                "options": [
                    "Easily on both sides",
                    "Can on both sides but with effort",
                    "One side only",
                    "Fingers almost touch but don't clasp ",
                    "Hands are far apart",
                ],
                "curve": [100, 82, 60, 40, 15],
                "weight": 0.3,
            },
        ],
    },
    {
        "name": "Body Composition",
        "questions": [
            {
                "description": "",
                "options": ["Male", "Female"],
                "question": "What is your biological sex?",
                "id": "biological_sex",
            },
            {
                "description": "",
                "question": "What's your age?",
                "id": "age",
                "type": "number",
            },
            {
                "description": "",
                "question": "What's your weight (kg)?",
                "id": "weight_kg",
                "type": "number",
            },
            {
                "description": "", 
                "question": "What's your height (cm)?",
                "id": "height_cm",
                "type": "number",
            },
            {
                "category": "metabolic",
                "curve": [100, 90, 75, 55, 25, None],
                "description": "",
                "options": [
                    "Under 12%",
                    "12-15%",
                    "15-20%",
                    "20-25%",
                    "Over 25%",
                    "Haven't measured / don't remember",
                ],
                "question": "What's your approximate body fat percentage?",
                "id": "body_fat_percentage",
                "insight": "Body composition",
                "weight": 0.2,
            },
            {
                "description": "",
                "question": "What's your waist circumference (cm)?",
                "id": "waist_circumference_cm",
                "type": "number",
            },
            {
                "category": "metabolic",
                "curve": [100, 70, 25, None],
                "description": "",
                "options": [
                    "Yes, it's low",
                    "Yes, it's moderate",
                    "Yes, it's high",
                    "Haven't measured / don't remember",
                ],
                "question": "What is your viceral fat level?",
                "id": "visceral_fat_level",
                "insight": "Visceral fat",
                "weight": 0.15,
            },
        ],
    },
    {
        "name": "Lifestyle",
        "questions": [
            {
                "category": "recovery",
                "curve": [100, 90, 65, 25],
                "description": "",
                "options": ["8+ hours ", "7-8 hours", "6-7 hours", "Under 6 hours"],
                "question": "How much sleep do you average per night?",
                "id": "average_sleep_hours",
                "insight": "Sleep duration",
                "weight": 0.15,
            },
            {
                "category": "nutrition",
                "curve": [100, 80, 55, 20],
                "description": "Includes plain water, sparkling water, or water infused with electrolytes.",
                "options": [
                    "Over 3 liters (approx. 100+ oz)",
                    "2-3 liters (approx. 70-100 oz)",
                    "1-2 liters (approx. 35-70 oz)",
                    "Under 1 liter (Less than 35 oz)",
                ],
                "question": "What is your daily water intake?",
                "id": "daily_water_intake",
                "insight": "Hydration",
                "weight": 0.15,
            },
            {
                "category": "nutrition",
                "curve": [100, 85, 55, 20],
                "description": "Calculated loosely as close to 0.7-1g of protein per pound of lean body weight.",
                "options": [
                    "Track precisely and hit it daily",
                    "Prioritize protein at every meal (high estimate)",
                    "Eat protein source occasionally",
                    "Don't track or prioritize protein at all",
                ],
                "question": "How intentionally do you hit your daily protein goal?",
                "id": "protein_goal_consistency",
                "insight": "Protein intake",
                "weight": 0.2,
            },
            {
                "category": "recovery",
                "curve": [100, 70, 30],
                "description": "",
                "options": ["Yes", "Sometimes", "No"],
                "question": "Do you go to bed within 30 minutes of the same time most nights?",
                "id": "consistent_bedtime",
                "insight": "Sleep consistency",
                "weight": 0.1,
            },
            {
                "category": "recovery",
                "curve": [100, 80, 55, 20],
                "description": "",
                "options": [
                    "9-10, I wake up ready",
                    "7-8, good on most days",
                    "5-6, takes a while to get going",
                    "1-4, I drag myself out of bed",
                ],
                "question": "How's your morning energy?",
                "id": "morning_energy",
                "insight": "Recovery & daytime energy",
                "weight": 0.15,
            },
            {
                "category": "recovery",
                "curve": [100, 70, 35, 10],
                "description": "",
                "options": ["10+ minutes daily", "Sometimes", "Rarely", "Never"],
                "question": "Do you get morning sunlight in the first hour of waking up?",
                "id": "morning_sunlight",
                "insight": "Circadian rhythm",
                "weight": 0.1,
            },
            {
                "category": "nutrition",
                "curve": [100, 80, 55, 20],
                "description": "One serving is roughly the size of your fist.",
                "options": [
                    "5+ servings",
                    "3-4 servings",
                    "1-2 servings",
                    "Rarely or never",
                ],
                "question": "How many servings of fruits and vegetables do you consume per day?",
                "id": "fruit_vegetable_servings",
                "insight": "Micronutrient intake",
                "weight": 0.2,
            },
            {
                "category": "nutrition",
                "curve": [100, 75, 45, 15],
                "description": "",
                "options": [
                    "Mostly whole foods (cooked or bought prepped)",
                    "Mix of whole foods, convenience, and processed",
                    "Mostly takeout, ordered, or pre-packaged meals",
                    "Grazing and snacking more than real meals",
                ],
                "question": "How would you describe your current diet?",
                "id": "diet_quality",
                "insight": "Overall diet quality",
                "weight": 0.2,
            },
            {
                "category": "recovery",
                "curve": [100, 75, 45, 15],
                "description": "",
                "options": [
                    "Low, I manage it well",
                    "Moderate, some days are rough",
                    "High, most days feel pressured",
                    "Constant, I feel overwhelmed regularly",
                ],
                "question": "How's your stress level?",
                "id": "stress_level",
                "insight": "Stress management",
                "weight": 0.15,
            },
            {
                "category": "nutrition",
                "curve": [100, 85, 60, 35, 15],
                "description": "",
                "options": [
                    "Perfect, barely need to wipe",
                    "Regular, no complaints",
                    "Inconsistent or occasional issues",
                    "Frequent bloating, discomfort, or irregularity",
                    "Daily problems",
                ],
                "question": "How are your bowel movements?",
                "id": "bowel_health",
                "insight": "Digestive health",
                "weight": 0.1,
            },
        ],
    },
    {
        "name": "Biometric Data",
        "questions": [
            {
                "category": "recovery",
                "curve": [100, 92, 80, 60, 30, None],
                "description": "",
                "options": [
                    "Under 50",
                    "50-55",
                    "56-60",
                    "61-70",
                    "Over 70",
                    "Haven't measured / don't remember",
                ],
                "question": "What is your resting heart rate?",
                "id": "resting_heart_rate",
                "insight": "Cardiovascular efficiency",
                "weight": 0.05,
            },
            {
                "category": "recovery",
                "curve": [100, 85, 65, 40, 20, None],
                "description": "",
                "options": [
                    "Over 100",
                    "70-100",
                    "50-69",
                    "30-49",
                    "Under 30",
                    "Haven't measured / don't remember",
                ],
                "question": "What is your HRV baseline?",
                "id": "hrv_baseline",
                "insight": "Recovery capacity",
                "weight": 0.05,
            },
            {
                "category": "recovery",
                "curve": [100, 85, 70, 40, None],
                "description": "",
                "options": [
                    "90%+",
                    "80-89%",
                    "70-79%",
                    "Under 70%",
                    "Haven't measured / don't remember",
                ],
                "question": "What's your average sleep score?",
                "id": "sleep_score",
                "insight": "Sleep quality",
                "weight": 0.15,
            },
            {
                "category": "recovery",
                "curve": [100, 85, 75, 30],
                "description": "",
                "options": [
                    "5-15 minutes",
                    "under 5 minutes",
                    "15-30 minutes",
                    "Over 30 minutes",
                ],
                "question": "How long does it take you to fall asleep?",
                "id": "sleep_latency",
                "insight": "Sleep onset",
                "weight": 0.1,
            },
            {
                "category": "cardio",
                "curve": [100, 85, 70, 50, 20, None],
                "description": "",
                "options": [
                    "Over 55",
                    "45-55",
                    "40-44",
                    "35-39",
                    "Under 35",
                    "Haven't measured / don't remember",
                ],
                "question": "What's your V02 max? (ml/kg/min)",
                "id": "vo2_max",
                "insight": "Cardiorespiratory fitness",
                "weight": 0.3,
            },
            {
                "category": "metabolic",
                "curve": [100, 85, 60, 25, None],
                "description": "",
                "options": [
                    "Under 120/80",
                    "120-129 systolic",
                    "130-139 or 80-89 diastolic",
                    "140+/90+",
                    "Haven't measured / don't remember",
                ],
                "question": "What's your blood pressure?",
                "id": "blood_pressure",
                "insight": "Blood pressure",
                "weight": 0.15,
            },
        ],
    },
    {
        "name": "Bloodwork",
        "questions": [
            {
                "category": "metabolic",
                "curve": [100, 85, 60, 25, None],
                "description": "",
                "options": [
                    "Under 0.5 mg/L",
                    "0.5-1.0 mg/L",
                    "1.0-3.0 mg/L",
                    "3+ mg/L",
                    "Haven't measured / don't remember",
                ],
                "question": "What's your hsCRP? (mg/L)",
                "id": "hscrp",
                "insight": "Systemic inflammation",
                "weight": 0.1,
            },
            {
                "category": "metabolic",
                "curve": [100, 85, 45, 10, None],
                "description": "",
                "options": [
                    "Glucose < 90 mg/dL · HbA1c < 5.2%",
                    "Glucose 90-99 · HbA1c 5.2-5.6%",
                    "Glucose 100-125 · HbA1c 5.7-6.4%",
                    "Glucose 126+ · HbA1c 6.5%+",
                    "Haven't measured / don't remember",
                ],
                "question": "What's your fasting glucose or HbA1c?",
                "id": "glucose_or_hba1c",
                "insight": "Blood sugar regulation",
                "weight": 0.2,
            },
            {
                "category": "nutrition",
                "curve": [100, 70, 30, None],
                "description": "",
                "options": [
                    "Over 8%",
                    "5-8%",
                    "Under 5%",
                    "Haven't measured / don't remember",
                ],
                "question": "What's your Omega-3 index?",
                "id": "omega_3_index",
                "insight": "Omega-3 status",
                "weight": 0.15,
            },
            {
                "category": "metabolic",
                "curve": [100, 80, 55, 20, None],
                "description": "",
                "options": [
                    "Over 60 mg/dL (1.55+ mmol/L)",
                    "50-59 mg/dL (1.30-1.54 mmol/L)",
                    "40-49 mg/dL (1.04-1.29 mmol/L)",
                    "Under 40 mg/dL (under 1.04 mmol/L)",
                    "Haven't measured / don't remember",
                ],
                "question": "What's your HDL (good) cholestrol? (ng/mL)",
                "id": "hdl_cholesterol",
                "insight": "HDL cholesterol",
                "weight": 0.1,
            },
            {
                "category": "metabolic",
                "curve": [100, 80, 50, 20, None],
                "description": "",
                "options": [
                    "Under 100 mg/dL (1.1 mmol/L)",
                    "100-149 mg/dL (1.1-1.7 mmol/L)",
                    "150-199 mg/dL (1.7-2.2 mmol/L)",
                    "200+ mg/dL (2.3+ mmol/L)",
                    "Haven't measured / don't remember",
                ],
                "question": "What's your triglyceride level?",
                "id": "triglyceride_level",
                "insight": "Triglyceride levels",
                "weight": 0.1,
            },
        ],
    },
]